FROM python:3.5

MAINTAINER Anoop Macharla <amacharla@sparkist.tech>

# Install supporting lib for MySQLdb for python3.5
RUN apt-get update && apt-get install -y \
	python3-dev \
	libmysqlclient-dev \
	zlib1g-dev

# tell the container what port will be using 
EXPOSE 5001

# Move respective files to right location based on configration
COPY web_app /web_app
COPY config_files/wait.sh /wait.sh

#python requirements
COPY config_files/requirements.txt /requirements.txt
RUN pip install -r requirements.txt \
	&& rm -rf /requirements.txt

# Install Supervisord a pid manager
RUN apt-get install -y supervisor

# clear apt data
RUN rm -rf /var/lib/apt/lists/*

# Custom Supervisord config
COPY config_files/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["./wait.sh", "db_server:3306","-s", "--", "/usr/bin/supervisord"]
