version: '3.3'

services:

  db_server:
    restart: on-failure
    image: url_shortener-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    ports:
      - "3306:3306"

  app_server:
    restart: on-failure
    image: url_shortener-python
    build:
      context: .
      dockerfile: Dockerfile-python
    networks:
      - backend
    ports:
      - "5001:5001"

  web_server:
    restart: on-failure
    image: url_shortener-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    networks:
      - backend
    ports:
      - "80:80"

networks:
    backend:

volumes:
  mysql_data:
