FROM mysql:5.7

MAINTAINER Anoop Macharla <amacharla@sparkist.tech>

# tell the container what port will be using 
EXPOSE 3306

# Custom mysql config
COPY config_files/mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf

# Setup data base access script
COPY config_files/db_access.sh /db_access.sh

# Setup data base config file
COPY config_files/dbsetup.sql /docker-entrypoint-initdb.d/dbsetup.sql

# forward request and error logs to docker log collector
#RUN ln -sf /dev/stderr /var/lib/mysql/error.log

# run user creation
#CMD ["./db_access.sh"]
